### ISSUE TITLE
Parser implementation

### ISSUE THREAD

**Issue by jlbernardo** [jlbernardo/minishell#10]
- [x] read user input
- [x] Create AST
- [x] Function to free the AST
- [x] Halt the parsing process once a syntax error is found
- [x] Norminette

**Comment by iuryr** [comment]
Commit 1f84aad61764ec3999e38f399eb784629cbcddc8 closes this issue.

**Comment by iuryr** [comment]
Parser needs to print error message when last token is a pipe.

Example: `echo |`

Most likely solved by an extra statement in lines 30~31 of parser.c. (but i will fuck up norminette check)

**Comment by iuryr** [comment]
8e17f34e2fc2cc75c3836ba9fdc7c9393d63f085 solves this.

**Comment by iuryr** [comment]
- [ ] Parser cannot break if input string is empty

**Comment by jlbernardo** [comment]
Integrate the following changes to parser:

- [ ] Quotes removal.
- [ ] Get path from command word.
