### ISSUE TITLE
Basic executor implementation (no builtins yet)

### ISSUE THREAD

**Issue by jlbernardo** [jlbernardo/minishell#23]
Main executor flux:
- Deal with pipes redirection.
- Deal with files redirection.
- Try to execute commands.

Suggestion of baby steps:
- Find the correct insertion of the executor in the existing code.
- Create the big picture logic of how the structures will be iterated.
- Implement the simplest case of execution.
- Complexify logic with different examples.
- Make sure to free what's allocated.

**Comment by iuryr** [comment]
Tentative roadmap to my prototype:

- [ ] Adjust parser function to flag when parsing was successful (only in this situation the executor will be called)
- [ ] Executor with no pipes (single command -> forks only for no BUILTINS)
- [ ] Executor with pipes (forks from everybody)

obs.: fist command only redirects output fd, last command only redirects input fd, everyboy in between redirects both input and output fd. Let's not bother with redirections other than pipes now

**Comment by iuryr** [comment]
fdbbbec Closes this.
